config/routes.rb
Rails.application.routes.draw do
  # Use the menu page as the root page
  root 'menu#index'
  # Available pages
  get 'menu/index'
  get 'simulator/thirtytwo'
  get 'simulator/sixtyfour'
  get 'simulator/sixtythree'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/simulator_controller.rb
class SimulatorController < ApplicationController
  def thirtytwo
    @height = 32
    @width = 32
  end

  def sixtyfour
    @height = 64
    @width = 64
  end

  def sixtythree
    @height = 63
    @width = 67
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/simulator_helper.rb
module SimulatorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatrixCacheSim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/simulator.html.erb
<!--
  simulator.html.erb
  Page hosting matrix simulations.
-->
<%
  # Class used for the algorithm buttons
  algo_btn_class = "btn btn-outline-success col-xl"
  # Class used for the simulation speed buttons
  speed_btn_class = "btn btn-outline-success col-xl"
  # Class used for dropdown buttons
  dropdown_btn_class = "btn btn-secondary dropdown-item"
%>
<!DOCTYPE html>
<html>
  <head>
    <title>Matrix Cache Sim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Root Container -->
    <div class="d-flex col-12 flex-column m-0 p-0">
      <!-- Title Bar -->
      <div class="d-flex col-12 justify-content-between align-items-stretch p-0">
        <!-- Back Button -->
        <%= link_to menu_index_path, class: "btn btn-secondary m-0 v-center" do %>
          <span>< Back</span>
        <% end %>
        <!-- Title -->
        <h1 class="flex-fill bg-primary text-center text-white m-0 p-2">
          <%= @height %>x<%= @width %> Matrix Simulator
        </h1>
        <!-- Dropdown Menu -->
        <div class="dropdown m-0">
          <button class="btn btn-secondary dropdown-toggle h-100"
            id="dropdownMenuButton" data-toggle="dropdown">
            Matrices
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to "32x32 Matrix", simulator_thirtytwo_path, class: dropdown_btn_class %>
            <%= link_to "64x64 Matrix", simulator_sixtyfour_path, class: dropdown_btn_class %>
            <%= link_to "63x67 Matrix", simulator_sixtythree_path, class: dropdown_btn_class %>
          </div>
        </div>
      </div>
      <!-- Matrices -->
      <div class="d-xl-flex justify-content-around flex-fill">
        <div class="d-lg-flex justify-content-center flex-fill matrix-container">
          <%= render partial: 'partials/matrix', locals: {
            name: "Matrix A",
            id: "matrixA",
            height: @height,
            width: @width
          } %>
          <%= render partial: 'partials/matrix', locals: {
            name: "Matrix B",
            id: "matrixB",
            height: @width,
            width: @height
          } %>
        </div>
        <%= render 'partials/stats-bar' %>
      </div>
      <!-- Algorithms & Options -->
      <div class="d-xl-flex py-2">
        <!-- Algorithms -->
        <div class="d-flex flex-fill flex-column align-items-stretch">
          <h3 class="bg-secondary text-center text-white mt-2 p-1">
            Available Algorithms
          </h3>
          <!-- Algorithm Buttons -->
          <div class="d-xl-flex justify-content-center px-2">
            <button class="<%= algo_btn_class %>" id="reset-btn">
              Stop/Reset
            </button>
            <button class="<%= algo_btn_class %>" id="naive-btn">
              Naive
            </button>
            <button class="<%= algo_btn_class %>" id="naive-blocked-4-btn">
              Naive Blocked-4
            </button>
            <button class="<%= algo_btn_class %>" id="naive-blocked-8-btn">
              Naive Blocked-8
            </button>
            <button class="<%= algo_btn_class %>" id="deferred-blocked-4-btn">
              Deferred Blocked-4
            </button>
            <button class="<%= algo_btn_class %>" id="deferred-blocked-8-btn">
              Deferred Blocked-8
            </button>
          </div>
        </div>
        <!-- Options -->
        <div class="d-flex flex-fill flex-column align-items-stretch mt-2">
          <h3 class="bg-secondary text-center text-white p-1">
            Simulation Speed
          </h3>
          <!-- Option Buttons -->
          <div class="d-sm-flex justify-content-center px-2">
            <button class="<%= speed_btn_class %>" id="speed-slowest-btn">
              Slowest
            </button>
            <button class="<%= speed_btn_class %>" id="speed-slow-btn">
              Slow
            </button>
            <button class="btn btn-success" id="speed-normal-btn">
              Normal
            </button>
            <button class="<%= speed_btn_class %>" id="speed-fast-btn">
              Fast
            </button>
            <button class="<%= speed_btn_class %>" id="speed-fastest-btn">
              Fastest
            </button>
          </div>
        </div>
      </div>
      <%= render 'partials/custom-algo' %>
    </div>
    <!-- Hidden elements used to store the matrix's size as part of the page -->
    <div class="d-none" id="matrixA-height"><%= @height %></div>
    <div class="d-none" id="matrixA-width"><%= @width %></div>
  </body>
</html>

app/views/menu/index.html.erb
<!--
  index.html.erb
  Page displayed when navigating to the application. Allows the user to
  switch to any of the available simulators.
-->
<%
  # Class used for buttons in the menu
  btn_class = "btn btn-primary w-100 my-1"
%>

<!-- Containers used to center the menu in the middle of the screen -->
<div class="root h-center">
  <div class="v-center col-xl-4 border border-primary border-thick m-4">
    <!-- Main Menu -->
    <div class="v-center align-items-stretch">
      <!-- Menu items container -->
      <div class="v-center align-items-stretch p-4">
        <h1 class="text-center">Available Simulators</h1>
        <%= link_to "32x32 Matrix", simulator_thirtytwo_path, class: btn_class %>
        <%= link_to "64x64 Matrix", simulator_sixtyfour_path, class: btn_class %>
        <%= link_to "63x67 Matrix", simulator_sixtythree_path, class: btn_class %>
      </div>
    </div>
    <!-- Planned Features & Known Issues -->
    <div class="d-xl-flex justify-content-around">
      <!-- Planned Features container -->
      <div class="col-xl-6">
        <h3>Planned Features:</h3>
        <ul>
          <li>Mobile Layout (In progress)</li>
          <li>Algorithm Verification</li>
          <li>Statistics Bar Revamp</li>
        </ul>
      </div>
      <!-- Known Issues container -->
      <div class="col-xl-6">
        <h3>Known Issues:</h3>
        <ul>
          <li>Layout breaks at some resolutions (fix in progress)</li>
        </ul>
      </div>
    </div>
    <!-- Version & Author -->
    <div class="d-flex justify-content-between p-2">
      <span>Written by Zach Wilson</span>
      <span>Last updated 11/29/2018</span>
    </div>
  </div>
</div>



app/views/partials/_custom-algo.html.erb
<!--
  _custom-algo.html.erb
  Partial used to display the information and text box for custom algorithm
  execution.
-->

<!-- Root Container -->
<div>
  <!-- Header -->
  <h3 class="bg-secondary text-center text-white py-1">Custom Algorithm</h3>
  <!-- Container for the text region and help bar -->
  <div class="d-xl-flex justify-content-between p-3">
    <!-- Text Region for the script -->
    <div class="d-flex flex-column flex-fill justify-content-center mx-4">
      <textarea rows="10" cols="140" style="resize:none" id="custom-func">
// Naive matrix transpose algorithm
for (var m = 0; m < Model.matrixA.y; ++m) {
  for (var n = 0; n < Model.matrixA.x; ++n) {
    Model.matrixB.set(m, n, Model.matrixA.get(n, m))
  }
}
      </textarea>
    <button class="btn btn-success my-2 py-2 px-4" id="run-custom">Run!</button>
    </div>
    <!-- Help bar -->
    <div class="d-flex flex-column border border-thick p-2">
      <h5>Usage:</h5>
      <p>Get MatrixA's Height (M): <code>Model.matrixA.y</code></p>
      <p>Get MatrixB's Height (M): <code>Model.matrixB.y</code></p>
      <p>Get a value from a matrix: <code>Model.matrixA.get(x, y)</code></p>
      <p>Set a value in a matrix: <code>Model.matrixA.set(x, y, value)</code></p>
    </div>
  </div>
</div>

app/views/partials/_matrix.html.erb
<!--
  _matrix.html.erb
  Partial used for rendering a matrix. The matrix will always fill the allotted
  space given to it.

  locals:
  :name (String) - Text to display as the name of the matrix
  :id (String) - ID to prepend to matrix elements IDs
  :height (Integer) - Height of the matrix
  :width (Integer) - Width of the matrix
-->
<!-- Root container for the Matrix -->
<div class="col-xl-6 p-2">
  <!-- Main container -->
  <div class="d-flex flex-column align-items-stretch
    border border-thick border-primary p-4 h-100" id="<%= id %>">
    <h3 class="bg-secondary p-2 text-center text-white"><%= name %></h3>
    <% (1..height).each do |y| %>
      <!-- Row container -->
      <div class="d-flex flex-fill flex-fix">
        <% (1..width).each do |x| %>
          <!-- Matrix element -->
          <div class="flex-fill flex-fix border border-primary
            matrix-element <%= "#{id}-element" %>">
            <span>&nbsp;</span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_stats-bar.html.erb
<!--
  _stats-bar.html.erb
  Displays a panel used for displaying cache statistics.
-->
<div class="col-xl-2 p-2">
  <div class="d-flex flex-column align-items-stretch bg-secondary
    text-white text-center p-2 flex-fix h-100">
    <h1>Algorithm Statistics</h1>
    <!-- Cache Hits -->
    <div>
      <span>Cache Hits: </span>
      <span id="cache-hits">0</span>
    </div>
    <!-- Cache Misses -->
    <div>
      <span>Cache Misses: </span>
      <span id="cache-misses">0</span>
    </div>
    <!-- Cache Evictions -->
    <div>
      <span>Cache Evictions: </span>
      <span id="cache-evictions">0</span>
    </div>
    <!-- Cache Usage -->
    <div>
      <span>Cache Usage: </span>
      <span id="cache-usage">0</span>
      <span>/</span>
      <span id="cache-size">0</span>
      <span>(</span>
      <span id="cache-percentage">0</span>
      <span>%)</span>
    </div>
    <!-- Cache Visualizer -->
    <div class="d-flex flex-wrap justify-content-around flex-fix my-2"
      id="cache-visualizer">
      <% (0..31).each do |index| %>
        <!-- Cache visualizer element -->
        <div class="d-flex col-sm-6 justify-content-between flex-fix px-1">
          <!-- Set number -->
          <span class="flex-fill flex-fix text-right"><%= index %>:&nbsp;&nbsp;</span>
          <!-- Status -->
          <div class="border col-9 cache-line-status flex-fix">
            &nbsp;
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/simulator/SixtyFour.html.erb
<h1>Simulator#SixtyFour</h1>
<p>Find me in app/views/simulator/SixtyFour.html.erb</p>

app/views/simulator/SixtyThree.html.erb
<h1>Simulator#SixtyThree</h1>
<p>Find me in app/views/simulator/SixtyThree.html.erb</p>

app/views/simulator/ThirtyTwo.html.erb
<!--
  thirtytwo.html.erb
  Page hosting the 32x32 matrix simulation.
-->
<%
  # Class used for the buttons at the bottom of the page
  btn_class = "btn btn-success mx-1"
%>
<!-- Root Container -->
<div class="d-flex flex-column h-100">
  <!-- Title Bar -->
  <h1 class="bg-primary text-center text-white p-2">
    32x32 Matrix Simulator
  </h1>
  <!-- Matrices -->
  <div class="d-flex justify-content-around flex-fill m-4">
    <%= render partial: 'partials/matrix', locals: {
      name: "Matrix A",
      id: "matrixA",
      height: 32,
      width: 32
    } %>
    <%= render partial: 'partials/matrix', locals: {
      name: "Matrix B",
      id: "matrixB",
      height: 32,
      width: 32
    } %>
  </div>
  <!-- Algorithms -->
  <div class="d-flex flex-column align-items-stretch mb-4">
    <h3 class="bg-secondary text-center text-white p-1">
      Available Algorithms
    </h3>
    <!-- Algorithm Buttons -->
    <div class="d-flex justify-content-center">
      <button class="<%= btn_class %>" id="reset-btn">
        Reset
      </button>
      <button class="<%= btn_class %>" id="naive-btn">
        Naive
      </button>
      <button class="<%= btn_class %>" id="naive-blocked-btn">
        Naive Blocked
      </button>
      <button class="<%= btn_class %>" id="deferred-blocked-btn">
        Deferred Blocked
      </button>
    </div>
  </div>
</div>

app/views/simulator/sixtyfour.html.erb
<h1>Simulator#SixtyFour</h1>
<p>Find me in app/views/simulator/SixtyFour.html.erb</p>

app/views/simulator/sixtythree.html.erb
<h1>Simulator#SixtyThree</h1>
<p>Find me in app/views/simulator/SixtyThree.html.erb</p>